### PR TITLE
skip properties that start with digit, cannot be mapped to function

### PR DESCRIPTION
**Pull request by mmolhoek**
might want to change this later to add am '_' infront of the property, so you could create a function out of it. now the property is lost, but at least the rest is ok.

### CODE REVIEW

**Comment by mmolhoek** [comment]
build failures are not caused by my change....

**Comment by godfat** [comment]
Haha, no worries. This is quite old, I haven't touched it for a while. It's not surprising it won't work given current status.

I'll take a look at this later. My first impression was we could still probably define those methods, via `define_method`. However I am not sure if this is a good idea, maybe we could just skip them as you did, of course.

**Comment by mmolhoek** [comment]
you should add sudo apt-get install postgresql-server-dev-9.3 libpq-dev to your travis setup to fix this  :)

**Comment by godfat** [comment]
Great, thanks for the tips for travis.

**Comment by mmolhoek** [comment]
np :)

**Comment by godfat** [comment]
I realized that this is passed to dm-core directly, and therefore we cannot control how the method would be created. So I just go ahead and did what you suggested: prefix an underscore. Could you please verify if this works for you? I am too lazy to write a test for this at the moment. I am no longer using datamapper now.

**Comment by mmolhoek** [comment]
Hi Lin,

it will be Monday before i can test. Just so you know :)

have a good weekend!

**Comment by godfat** [comment]
ok, thanks for letting me know.

Have a good weekend.

**Pull request merged**
